[general]
# mode = 1
# 循环模式：1=顺序播放, 2=随机, 3=随机不重复
# current_wallpaper_id = 2965361511
# current_wallpaper_id = 2894972488
# interval = 60
# 更换间隔时间（秒）
# interval = 6 # 更换间隔时间（秒）
log_file = "/home/narcissus/linux-wallpaperengine.log"
picked_types = ["video"]
skipped_types = ["application"]
play_list_name = "test"
wallpapers_dir = "/home/narcissus/.local/share/Steam/steamapps/workshop/content/431960/"
wallpaperengine_config_file = "/home/narcissus/.local/share/Steam/steamapps/common/wallpaper_engine/config.json"

[play_command]
base_command = "linux-wallpaperengine"
log_file = "/home/narcissus/.config/wallpaperengine/linux-wallpaperengine.log"
silent = true
# volume = 50
# noautomute = true
# noautomute =
# no_audio_processing = true
# no_audio_processing =
# screen_root = ["eDP-1", "HDMI-A-1"]
screen_root = ["HDMI-A-1", "eDP-1"]
# screen_root = ["eDP-1"]
# window = true
# window =
fps = 144
# assets_dir =
# screenshot = true
# screenshot =
# list_propertites = true
# list_propertites =
# set_property = ("" "")
# set_property =
# no_fullscreen_pause = true
# no_fullscreen_pause =
disable_mouse = true
# disable_mouse =
scaling = "fill"
# scaling = "fit"
# scaling = "stretch"
clamping = "border"
